
screen -S 2017-04 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2017-04.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2017-05 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2017-05.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2017-06 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2017-06.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2017-07 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2017-07.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2017-08 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2017-08.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2017-09 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2017-09.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2017-10 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2017-10.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2017-11 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2017-11.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2017-12 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2017-12.pgn.bz2 /datadrive/new_board_csvs'

screen -S 2018-01 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2018-01.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2018-02 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2018-02.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2018-03 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2018-03.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2018-04 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2018-04.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2018-05 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2018-05.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2018-06 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2018-06.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2018-07 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2018-07.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2018-08 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2018-08.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2018-09 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2018-09.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2018-10 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2018-10.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2018-11 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2018-11.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2018-12 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2018-12.pgn.bz2 /datadrive/new_board_csvs'

screen -S 2019-01 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2019-01.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2019-02 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2019-02.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2019-03 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2019-03.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2019-04 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2019-04.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2019-05 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2019-05.pgn.bz2 /datadrive/new_board_csvs'
screen -S 2019-06 -dm bash -c '/home/reidmcy/anaconda3/bin/python3 make_month_csv.py /datadrive/raw_pgns/lichess_db_standard_rated_2019-06.pgn.bz2 /datadrive/new_board_csvs'
